name: Release

on:
  [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: JCorrea13/MyFirstAction@main
        id: thismyid2
        name: HelloActionWithDocker
        with:
          action-type: 'Release'
