name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: unosquare/release-npm-package
          token: ${{ secrets.GITHUBPAT }}
      #- uses: unosquare/release-npm-package@da53983a6ac6b3c5873c73e7f6428ff6840d4d57
        #id: thismyid
        #name: ReleasePackage
        #with:
          #release-version: Patch
